---
kind: pipeline
name: hashiapp_pr

platform:
  os: linux
  arch: amd64

steps:
- name: mvn
  image: maven:3.6.0-jdk-8
  commands:
  - mvn dependency:resolve
  - mvn verify
  - mvn package

trigger:
  event:
  - pull_request

---
kind: pipeline
name: hashiapp

platform:
  os: linux
  arch: amd64

steps:
- name: mvn
  image: maven:3.6.0-jdk-8
  commands:
  - mvn dependency:resolve
  - mvn verify
  - mvn package

trigger:
  branch:
  - master

---
kind: signature
hmac: c4aca4c351f522baa054b40e31186b2c4b6428e9ea216c712cda2df60f186054

...
